- name: Update system
  hosts: beelink
  become: true

  tasks:
    - name: Update apt cache and perform full upgrade
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
        upgrade: dist
        autoremove: true
        autoclean: true
      register: upgrade_result

    - name: Show upgraded packages
      ansible.builtin.debug:
        msg: "{{ upgrade_result.stdout_lines }}"
      when: upgrade_result.stdout_lines is defined

    - name: Check if reboot is required
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Notify if reboot is required
      ansible.builtin.debug:
        msg: "Reboot is required."
      when: reboot_required.stat.exists

    - name: Notify if no reboot is required
      ansible.builtin.debug:
        msg: "No reboot required."
      when: not reboot_required.stat.exists
